### -------------------------------
### Vault
### -------------------------------
vercel_api_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  38663165633461653634303463383661393038353237356233383262653531643963353630376262
  3961386537383762336164643163313766373537383962390a303561646361303839653439353163
  35383439346334653137383035333062373330383830633262643834666432306236636362613034
  3635333632333839340a336338626462333230366464656435343862653436306638623933646333
  63353235643130323431363430386639643433373530643130643262396662393662