nfs_enabled: true

### -------------------------------
### Directories
### -------------------------------
drive_root: "{{ server_root }}/drive"

### -------------------------------
### Vault
### -------------------------------
sc_desktop_tailscale_ip: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34336531663434373135353564393063373065386263366234613231663864393037663661663431
  3631303535313732383237383339353539346635393332360a336431323862366462316138626132
  30373565653664326330393563633265313439323234366431343766386635336238653033643736
  3962643065316639660a663737653264353063323230313233326561656636633537383038666162
  3434

sc_framework_laptop_tailscale_ip: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32633066373433303030623363316265353365396239623031656333613130363533366164386162
  3961396634383865626233613561373563346634383432360a363463623865326263656235666630
  33333131363932626535393266626538663631653130353064646363376535346566323438383864
  3035643962613832350a636465643161376231653465626233626239356537333632633930303737
  3763